### ISSUE TITLE
Event query works differently on emulator and devnet

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-go-sdk#95] opened 2020-09-10 20:22 UTC
### Problem

When doing an query to get events without specifying a type field the following happends:

 - emulator returns all event types
 - devnet returns no events 

### Steps to Reproduce 

Perform and event query with no parameters specified in the event query struct.

### Acceptance Criteria

Document the difference. Return error if not allowed.

**Comment by turbolent** [comment] 2020-09-10 20:44
@vishalchangrani Is it possible that the behaviour in the Access API is incorrectly different?

**Comment by cybercent** [comment] 2020-09-16 08:47
@bjartek I had this same issue a while back.
AFAIK querying events with no type will not be possible on devnet, testnet and mainnet.
For consistency, the Emulator should not allow querying events with no type.

**Comment by vishalchangrani** [comment] 2020-09-16 16:22
Yes, currently `devnet` and `mainnet` by design return nothing if no even type is specified. I am investigating if that can be changed to behave similar to the emulator by return all events.

**Comment by vishalchangrani** [comment] 2020-09-16 17:17
Had a chat about this internally and it was recommended that the emulator code be changed to mimic the `devnet`/`mainnet` behaviour which is to not return any event if event type is empty.
While returning all events should be an option, the concern is that in some cases the event list may be large and may cause a performance issue. Hence, the ability to return all events should be provided after a pagination scheme has been implemented for events.

**Comment by bjartek** [comment] 2020-09-16 18:10
Fair enough. But are you going to theow an error if you call the api with no event type?

**Comment by vishalchangrani** [comment] 2020-09-16 18:58
that is actually a good idea. Will throw an error if even type is an empty string.

**Comment by vishalchangrani** [comment] 2020-09-17 23:25
https://github.com/dapperlabs/flow-emulator/issues/99 - PR

**Comment by psiemens** [comment] 2020-12-11 06:33
This has since been fixed in the emulator to match the behaviour that @vishalchangrani described: https://github.com/onflow/flow-emulator/commit/1fe4e667a443dc76e4c6f91facd0e3e07d5beb4d

**Closed by psiemens** 2020-12-11 06:33 UTC
Labels: bug
